### ISSUE TITLE
Unknown camera: make: "Canon", model: "Canon EOS R5 C", mode: "raw"

### ISSUE THREAD

**Issue by pierre1618** [dnglab/dnglab#299] opened 2023-05-05 14:16 UTC
Hi, i got a problem when i"m trying to convert a CR3 file to DNG, the convertion failed and i got the error 
Unknown camera: make: "Canon", model: "Canon EOS R5 C", mode: "raw", this is strange because the camera "Canon EOS R5" are in the list of supported format (maybe the problem is because of the C).

version=dnglab 0.5.1

**Comment by lclevy** [comment] 2023-05-05 14:35
These are different models

**Comment by cytrinox** [comment] 2023-05-05 18:16
@pierre1618 Please provide a sample set of raw files: https://github.com/dnglab/dnglab/blob/main/CONTRIBUTE_SAMPLES.md#canon-cr3
It should be easy to add support for it.

**Comment by pierre1618** [comment] 2023-05-08 08:12
I unfortunately don't have access to the camera directly but if someone has access to it that would be very nice !

**Comment by cytrinox** [comment] 2024-04-01 12:25
duplicate of #297

**Closed by cytrinox** 2024-04-01 12:25 UTC
