### ISSUE TITLE
.CR3 files converted from burst are massive in size

### ISSUE THREAD

**Issue by bverkron** [dnglab/dnglab#460] opened 2024-07-15 04:27 UTC
Tried dnglab for the first time on some .CR3 burst files shot on a Canon R6 MK II and each of the extracted, individual .CR3 raw files were larger in file size than the original burst... they were over 900MB each

This is the command output. See below for screenshot of the files that were output.

```shell
% ./dnglab convert --image-index=all JW8A3256.CR3 /Volumes/Data/working/photos/2024/2024-07/2024-07-14 

Writing DNG output file: /Volumes/Data/working/photos/2024/2024-07/2024-07-14/JW8A3256_0001.dng
Writing DNG output file: /Volumes/Data/working/photos/2024/2024-07/2024-07-14/JW8A3256_0002.dng
Writing DNG output file: /Volumes/Data/working/photos/2024/2024-07/2024-07-14/JW8A3256_0000.dng
Writing DNG output file: /Volumes/Data/working/photos/2024/2024-07/2024-07-14/JW8A3256_0004.dng
Writing DNG output file: /Volumes/Data/working/photos/2024/2024-07/2024-07-14/JW8A3256_0003.dng
Writing DNG output file: /Volumes/Data/working/photos/2024/2024-07/2024-07-14/JW8A3256_0007.dng
Writing DNG output file: /Volumes/Data/working/photos/2024/2024-07/2024-07-14/JW8A3256_0005.dng
Writing DNG output file: /Volumes/Data/working/photos/2024/2024-07/2024-07-14/JW8A3256_0006.dng
Writing DNG output file: /Volumes/Data/working/photos/2024/2024-07/2024-07-14/JW8A3256_0008.dng
Writing DNG output file: /Volumes/Data/working/photos/2024/2024-07/2024-07-14/JW8A3256_0014.dng
Writing DNG output file: /Volumes/Data/working/photos/2024/2024-07/2024-07-14/JW8A3256_0013.dng
Writing DNG output file: /Volumes/Data/working/photos/2024/2024-07/2024-07-14/JW8A3256_0010.dng
Writing DNG output file: /Volumes/Data/working/photos/2024/2024-07/2024-07-14/JW8A3256_0015.dng
Writing DNG output file: /Volumes/Data/working/photos/2024/2024-07/2024-07-14/JW8A3256_0011.dng
Writing DNG output file: /Volumes/Data/working/photos/2024/2024-07/2024-07-14/JW8A3256_0012.dng
Writing DNG output file: /Volumes/Data/working/photos/2024/2024-07/2024-07-14/JW8A3256_0009.dng
Writing DNG output file: /Volumes/Data/working/photos/2024/2024-07/2024-07-14/JW8A3256_0017.dng
Writing DNG output file: /Volumes/Data/working/photos/2024/2024-07/2024-07-14/JW8A3256_0019.dng
Writing DNG output file: /Volumes/Data/working/photos/2024/2024-07/2024-07-14/JW8A3256_0020.dng
Writing DNG output file: /Volumes/Data/working/photos/2024/2024-07/2024-07-14/JW8A3256_0016.dng
Writing DNG output file: /Volumes/Data/working/photos/2024/2024-07/2024-07-14/JW8A3256_0023.dng
Writing DNG output file: /Volumes/Data/working/photos/2024/2024-07/2024-07-14/JW8A3256_0018.dng
Writing DNG output file: /Volumes/Data/working/photos/2024/2024-07/2024-07-14/JW8A3256_0021.dng
Writing DNG output file: /Volumes/Data/working/photos/2024/2024-07/2024-07-14/JW8A3256_0022.dng
^C
```
It took like 20-30 minutes and ate up over 25GB of space on my drive and it was still going. I had to kill it. The highlighted file at the top is the original .CR3 burst and the ones below are the individual images that had been extracted up to the point I killed the command.

<img width="660" alt="image" src="https://github.com/user-attachments/assets/7b707c08-b779-4bd9-8867-05f9f00a081c">

**Comment by cytrinox** [comment] 2024-07-15 06:42
Duplicate of #345

**Closed by cytrinox** 2024-07-15 06:42 UTC
